export default [
  {
    "id": 1,
    "CategoryId": 14,
    "categoryName": "Cemilan",
    "sku": "MHZVTK",
    "name": "Ciki ciki",
    "description": "Ciki ciki yang super enak, hanya di toko klontong kami",
    "weight": 500,
    "width": 5,
    "length": 5,
    "height": 5,
    "image": "https://cf.shopee.co.id/file/7cb930d1bd183a435f4fb3e5cc4a896b",
    "harga": 30000
  },
  {
    "id": 2,
    "CategoryId": 14,
    "categoryName": "Cemilan",
    "sku": "MHZVTK",
    "name": "Ciki ciki",
    "description": "Ciki ciki yang super enak, hanya di toko klontong kami",
    "weight": 500,
    "width": 5,
    "length": 5,
    "height": 5,
    "image": "https://cf.shopee.co.id/file/7cb930d1bd183a435f4fb3e5cc4a896b",
    "harga": 30000
  },
  {
    "id": 3,
    "CategoryId": 14,
    "categoryName": "Cemilan",
    "sku": "MHZVTK",
    "name": "Ciki ciki",
    "description": "Ciki ciki yang super enak, hanya di toko klontong kami",
    "weight": 500,
    "width": 5,
    "length": 5,
    "height": 5,
    "image": "https://cf.shopee.co.id/file/7cb930d1bd183a435f4fb3e5cc4a896b",
    "harga": 30000
  },
  {
    "id": 4,
    "CategoryId": 14,
    "categoryName": "Cemilan",
    "sku": "MHZVTK",
    "name": "Ciki ciki",
    "description": "Ciki ciki yang super enak, hanya di toko klontong kami",
    "weight": 500,
    "width": 5,
    "length": 5,
    "height": 5,
    "image": "https://cf.shopee.co.id/file/7cb930d1bd183a435f4fb3e5cc4a896b",
    "harga": 30000
  },
  {
    "id": 5,
    "CategoryId": 14,
    "categoryName": "Cemilan",
    "sku": "MHZVTK",
    "name": "Ciki ciki",
    "description": "Ciki ciki yang super enak, hanya di toko klontong kami",
    "weight": 500,
    "width": 5,
    "length": 5,
    "height": 5,
    "image": "https://cf.shopee.co.id/file/7cb930d1bd183a435f4fb3e5cc4a896b",
    "harga": 30000
  },
  {
    "id": 6,
    "CategoryId": 14,
    "categoryName": "Cemilan",
    "sku": "MHZVTK",
    "name": "Ciki ciki",
    "description": "Ciki ciki yang super enak, hanya di toko klontong kami",
    "weight": 500,
    "width": 5,
    "length": 5,
    "height": 5,
    "image": "https://cf.shopee.co.id/file/7cb930d1bd183a435f4fb3e5cc4a896b",
    "harga": 30000
  },
  {
    "id": 7,
    "CategoryId": 14,
    "categoryName": "Cemilan",
    "sku": "MHZVTK",
    "name": "Ciki ciki",
    "description": "Ciki ciki yang super enak, hanya di toko klontong kami",
    "weight": 500,
    "width": 5,
    "length": 5,
    "height": 5,
    "image": "https://cf.shopee.co.id/file/7cb930d1bd183a435f4fb3e5cc4a896b",
    "harga": 30000
  },
  {
    "id": 8,
    "CategoryId": 14,
    "categoryName": "Cemilan",
    "sku": "MHZVTK",
    "name": "Ciki ciki",
    "description": "Ciki ciki yang super enak, hanya di toko klontong kami",
    "weight": 500,
    "width": 5,
    "length": 5,
    "height": 5,
    "image": "https://cf.shopee.co.id/file/7cb930d1bd183a435f4fb3e5cc4a896b",
    "harga": 30000
  },
  {
    "id": 9,
    "CategoryId": 14,
    "categoryName": "Cemilan",
    "sku": "MHZVTK",
    "name": "Ciki ciki",
    "description": "Ciki ciki yang super enak, hanya di toko klontong kami",
    "weight": 500,
    "width": 5,
    "length": 5,
    "height": 5,
    "image": "https://cf.shopee.co.id/file/7cb930d1bd183a435f4fb3e5cc4a896b",
    "harga": 30000
  },
  {
    "id": 10,
    "CategoryId": 14,
    "categoryName": "Cemilan",
    "sku": "MHZVTK",
    "name": "Ciki ciki",
    "description": "Ciki ciki yang super enak, hanya di toko klontong kami",
    "weight": 500,
    "width": 5,
    "length": 5,
    "height": 5,
    "image": "https://cf.shopee.co.id/file/7cb930d1bd183a435f4fb3e5cc4a896b",
    "harga": 30000
  },
  {
    "id": 11,
    "CategoryId": 14,
    "categoryName": "Cemilan",
    "sku": "MHZVTK",
    "name": "Ciki ciki",
    "description": "Ciki ciki yang super enak, hanya di toko klontong kami",
    "weight": 500,
    "width": 5,
    "length": 5,
    "height": 5,
    "image": "https://cf.shopee.co.id/file/7cb930d1bd183a435f4fb3e5cc4a896b",
    "harga": 30000
  },
  {
    "id": 12,
    "CategoryId": 14,
    "categoryName": "Cemilan",
    "sku": "MHZVTK",
    "name": "Ciki ciki",
    "description": "Ciki ciki yang super enak, hanya di toko klontong kami",
    "weight": 500,
    "width": 5,
    "length": 5,
    "height": 5,
    "image": "https://cf.shopee.co.id/file/7cb930d1bd183a435f4fb3e5cc4a896b",
    "harga": 30000
  },
  {
    "id": 13,
    "CategoryId": 14,
    "categoryName": "Cemilan",
    "sku": "MHZVTK",
    "name": "Ciki ciki",
    "description": "Ciki ciki yang super enak, hanya di toko klontong kami",
    "weight": 500,
    "width": 5,
    "length": 5,
    "height": 5,
    "image": "https://cf.shopee.co.id/file/7cb930d1bd183a435f4fb3e5cc4a896b",
    "harga": 30000
  },
  {
    "id": 14,
    "CategoryId": 14,
    "categoryName": "Cemilan",
    "sku": "MHZVTK",
    "name": "Ciki ciki",
    "description": "Ciki ciki yang super enak, hanya di toko klontong kami",
    "weight": 500,
    "width": 5,
    "length": 5,
    "height": 5,
    "image": "https://cf.shopee.co.id/file/7cb930d1bd183a435f4fb3e5cc4a896b",
    "harga": 30000
  },
];
